version: "3.9"
services:
 restaurant-service:
  image: r0930134/qrcodequiz
  ports:
    - "8000:8000"

 mysql:
  image: mysql:latest
  volumes:
    - quiz-data:/code/mysqldb
  environment:
    MYSQL_ROOT_PASSWORD: abc123!
    MYSQL_DATABASE: quizdb

volumes:
  restaurant_data: